import Head from 'next/head';
import Image from 'next/image';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';

export default function Home({ newsResults }) {
  return (
    <div className="flex mx-auto min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Sidebar */}
      <Sidebar />

      {/* Feed */}
      <Feed />

      {/* Widgets */}
      <Widgets articles={newsResults.articles} />

      {/* Modal */}

    </div>
  )
}
// https://saurav.tech/NewsAPI/top-headlines/category/business/in.json

export async function getServerSideProps(){
  const newsResults = await fetch(
    'https://saurav.tech/NewsAPI/top-headlines/category/health/in.json'
    ).then(res=>res.json());
  return {
    props: {
      newsResults,
    }
  }
}